title: RedCupd
description: "Redcup: An awesome Theme for Jekyll"

url: http://roachhd.github.io/redcup/
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Katie Ball
  disqus_shortname: roachhd
  twitter: _mektball
